# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jef DeWitt | Web Developer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, I'm Jef DeWitt, Web Developer and weekend software engineer in Louisville Kentucky. I
  specialize in PHP, AngularJS, and mobile development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jefdewitt.com" # the base hostname & protocol for your site
username:                jefdewitt
github_username:         jefdewitt
instagram_username:      jefdewitt
facebook_username:       jefdewitt
stackoverflow_username:  jefdewitt
codepen_username:        jefdewitt
email_username:          jefdewitt
linkedin_username:       jefdewitt

# Build settings
markdown: kramdown

# Syntax highlighting
highlighter: rouge

# New permalink structure for posts
permalink: /archive/:title/

# New document type
# Source: https://jekyllrb.com/docs/collections/
# More on collections here: http://ben.balter.com/2015/02/20/jekyll-collections/
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Plugins
# gems: [jekyll-paginate]
# This will require each of these gems automatically.
# paginate: 5

exclude:
  - trackerkeeper/node_modules/ngtouch/contributions.md
  - trackerkeeper/node_modules/ngtouch/roadmap.md
  - trackerkeeper/node_modules/angular-ui-router/CONTRIBUTING.md
  - package.json
  - node_modules
  - gulpfile.js
